### PR TITLE
feat: desktop app with tauri

### PR DESCRIPTION
**Pull request by Wybxc**
Related issue: #24 

Current Progress:

- [x] Search by local index
- [ ] Download via IPFS RPC
- [ ] Automatically fetch index files from IPFS/GitHub
- [x] Configuation UI

### CODE REVIEW

**Comment by zu1k** [comment]
It looks like the desktop version is primed to run, can we merge it now for the first stage?

And the rest of the work can be achieved with another new PR.

**Comment by Wybxc** [comment]
> It looks like the desktop version is primed to run, can we merge it now for the first stage?
> 
> And the rest of the work can be achieved with another new PR.

OK.

**Comment by zu1k** [comment]
Can you replace the icon with a blank one for now, we need a new icon and I have opened an issue #31 

You can delete my init desktop commit to do a force push and change the author information of the desktop to yours

**Comment by zu1k** [comment]
Or just change the icon and author info, then I do a squash and merge, but some information will be lost in the commit log

**Comment by zu1k** [comment]
It looks good, is it ready to be merged?

**Comment by Wybxc** [comment]
> It looks good, is it ready to be merged?

I think so.

**Comment by zu1k** [comment]
Thank you very much for your excellent work

**Pull request merged**
